### ISSUE TITLE
Need a way to retrieve security Hub Details by passing AWS-ACCOUNT-ID and Regions combination

### ISSUE THREAD

**Issue by kailasandhale** [tenable/Security-Hub#14]
Currently, we have a way to retrieve the Security Hub integration Details by Aws Account ID, but there is no way to check if the security hub is enabled for particular aws account ID and region (or set of regions) combination and get the relevant details.

**Comment by kailasandhale** [comment]
@SteveMcGrath  Could you please help here

**Comment by SteveMcGrath** [comment]
Honestly I don't have a good answer on this.  its not something specific to the integration, more of a "how do I know what regions have SecHub".

Have you looked at the aws CLI? 

https://docs.aws.amazon.com/cli/latest/reference/securityhub/describe-hub.html
