### ISSUE TITLE
ImportError: cannot import name 'TenableException' from 'tenable.errors'

### ISSUE THREAD

**Issue by TheFlexican** [tenable/Security-Hub#19]
The script tries to import TenableException from tenable.errors'. 

This method does not exist in the current release of pyTenable errors.py

There is a class that is suppose to do something with the exception, but it's never called.

class SecHubError(TenableException):
    pass

**Comment by alpesh-te** [comment]
It has fixed with this PR https://github.com/tenable/Security-Hub/pull/21. Hence I am closing this issue
