### ISSUE TITLE
Clarification on the purpose of this repo

### ISSUE THREAD

**Issue by mr-beerkiss** [tenable/Security-Hub#34]
Hi,

I'm confused by the documentation for this repo. The README implies that _any_ tenable finding can be shipped to AWS Security Hub. 

> This tool is designed to consume Tenable.io asset and vulnerability data, transform that data into the AWS Security Hub Finding format, and then upload the resulting data into AWS Security Hub.

However, [this documentation in the code](https://github.com/tenable/Security-Hub/blob/master/sechubingest.py#L57) implies that only AWS asset classes are considered.  [This comment](https://github.com/tenable/Security-Hub/blob/master/sechubingest.py#L281) specifically states that if no AWS assets are found then there is no point in search for vulnerabilities. 

I assume the code is correct and it's not possible to for AWS SecurityHub to ingest vulnerability data gather from non-AWS assets. If so, can the READMe be updated to clarify this point.

**Comment by SteveMcGrath** [comment]
This is correct, as SecurityHub expects that all findings that ingested must be related to an AWS asset of some sort, we are required to make the same consideration on our end.
